require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/readings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Reading. As you add validations to Reading, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Reading.create! valid_attributes
      get readings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reading = Reading.create! valid_attributes
      get reading_url(reading)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reading_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      reading = Reading.create! valid_attributes
      get edit_reading_url(reading)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Reading" do
        expect {
          post readings_url, params: { reading: valid_attributes }
        }.to change(Reading, :count).by(1)
      end

      it "redirects to the created reading" do
        post readings_url, params: { reading: valid_attributes }
        expect(response).to redirect_to(reading_url(Reading.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Reading" do
        expect {
          post readings_url, params: { reading: invalid_attributes }
        }.to change(Reading, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post readings_url, params: { reading: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reading" do
        reading = Reading.create! valid_attributes
        patch reading_url(reading), params: { reading: new_attributes }
        reading.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reading" do
        reading = Reading.create! valid_attributes
        patch reading_url(reading), params: { reading: new_attributes }
        reading.reload
        expect(response).to redirect_to(reading_url(reading))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        reading = Reading.create! valid_attributes
        patch reading_url(reading), params: { reading: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reading" do
      reading = Reading.create! valid_attributes
      expect {
        delete reading_url(reading)
      }.to change(Reading, :count).by(-1)
    end

    it "redirects to the readings list" do
      reading = Reading.create! valid_attributes
      delete reading_url(reading)
      expect(response).to redirect_to(readings_url)
    end
  end
end
